### ISSUE TITLE
NAT UdpBlocked

### ISSUE THREAD

**Issue by leopold7** [danube533/koolss-udp-separate#2]
你好，我安装了这个插件后，出现了如下问题，你能帮我分析下可能出错的点吗？

### 客户端版本：
openwrt: Openwrt Koolshare mod V2.31 r10822-50aa0525d1
koolss：koolss for OpenWRT/LEDE 2.2.3
udp2raw：20180225
UDPspeeder：v2

#### 客户端
1. 开启【分离TCP&UDP】之后，我的NAT类型就变为 UdpBlocked 了，能正常访问Google，无法进入游戏，说明【TCP连接】是没有问题的。

开启截图：
![image](https://user-images.githubusercontent.com/77429266/155500579-caee7a15-94b4-42ff-9321-0376286605e3.png)

NAT测试截图如下：
![image](https://user-images.githubusercontent.com/77429266/155497035-d24221c0-8f72-4965-9163-288fb217d9d5.png)

流量：
![image](https://user-images.githubusercontent.com/77429266/155499704-9c7e016c-a271-4bf5-af23-5441dbb29da0.png)

相关命令如下：
![image](https://user-images.githubusercontent.com/77429266/155497533-4e80a017-fd6b-4890-8f2c-bc9a7481dcb3.png)

2.关闭【分离TCP&UDP】之后，我的NAT类型就变为 FullCone 了，能正常访问Google，正常进入游戏
NAT测试截图如下：
![image](https://user-images.githubusercontent.com/77429266/155497777-cadd9c9c-e9de-40bf-91a8-cf4c4c0d51dd.png)

流量：
![image](https://user-images.githubusercontent.com/77429266/155499173-0cc77f5b-73e6-4e41-9e6f-41470b7ca21e.png)

相关命令如下：
![image](https://user-images.githubusercontent.com/77429266/155498194-0306fc84-ce91-4e6f-a667-d03bf20c98ac.png)

3.openwrt防火墙

![image](https://user-images.githubusercontent.com/77429266/155498929-d8f0e85e-6245-407f-b4f6-a28a8ebed89c.png)

#### 服务端
1. udpraw
/opt/udp2raw/udp2raw_amd64 -s -l 0.0.0.0:30001 -r 127.0.0.1:30002 --raw-mode faketcp -a -k "passwd"

2. udpspeeder
/opt/udpspeeder/speederv2_amd64 -s -l 0.0.0.0:30002 -r 127.0.0.1:51000   -k "passwd" --mode 0 -f 2:4 --timeout 0

已在防火墙中开启了【全部UDP端口】，以及【TCP 30001、9090（ss端口）】。

谢谢你看到这里，期待你的答复。

**Comment by leopold7** [comment]
突然发现服务端的udpspeeder端口指向错误，原先测试后一直没有修改，一直以为是客户端这边的问题，抱歉打扰了。

**Comment by danube533** [comment]
✌️✌️✌️
